In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Catlyn'],
        'Age': [24, 30, 45], 
        'Calls': [24, 30, 45]}


In [88]:
data['Calls'][2]=5555
data

{'Name': ['Alice', 'Bob', 'Catlyn'],
 'Age': [24, 30, 45],
 'Calls': [24, 30, 5555]}

In [89]:
dfa = pd.DataFrame(data, copy=False)
dfa

Name  Age  Calls
0   Alice   24     24
1     Bob   30     30
2  Catlyn   45   5555

In [90]:
dfb = pd.DataFrame(data, copy=True)
dfb

Name  Age  Calls
0   Alice   24     24
1     Bob   30     30
2  Catlyn   45   5555

`copy=False` means that df will reference the original data dictionary and will not create a new copy of the data.

`Copy=True`: Creates a new copy of the `data`, so modifications to the df DataFrame will not affect the original `data` dictionary

Copy-on-Write will become the new default in pandas 3.0. This means that chained indexing will never work.

In [58]:

import numpy as np

np.random.seed(0)
arr = np.random.randint(10, size=(3, 3))
print(arr)

df1 = pd.DataFrame(arr, copy=False)
df2 = pd.DataFrame(arr, copy=True)

[[5 0 3]
 [3 7 9]
 [3 5 2]]


In [59]:
# Change the first cell of the numpy array to -999
arr[0, 0] = 999

In [107]:
print(df1)
print('\n')
print(df2)

     0  1  2
0  999  0  3
1    3  7  9
2  200  5  2


     0    1  2
0    5    0  3
1    3    7  9
2  200  200  2


In [93]:
df1[0][2]=200
df1

C:\Users\devid\AppData\Local\Temp\ipykernel_27236\3165588094.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1[0][2]=200


0  1  2
0  999  0  3
1    3  7  9
2  200  5  2

In [94]:
arr

array([[999,   0,   3],
       [  3,   7,   9],
       [200,   5,   2]])

In [95]:
df2

0  1  2
0  5  0  3
1  3  7  9
2  3  5  2

In [98]:
df2[1][2]=200
df2

C:\Users\devid\AppData\Local\Temp\ipykernel_27236\3054820945.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df2[1][2]=200


0    1  2
0    5    0  3
1    3    7  9
2  200  200  2

In [99]:
arr

array([[999,   0,   3],
       [  3,   7,   9],
       [200,   5,   2]])