In [18]:
import numpy as np

array1 = np.array([[1,2,3],[4,5,6]]) # 2d array matrix

arr2= np.array([[[1,2,3],
[3,4,5]],[[1,2,3],
[3,4,5]]])

print(array1)

[[1 2 3]
 [4 5 6]]


In [28]:
print(array1.ndim)
print(array1.shape)

2
(2, 3)


In [10]:
arr1 = np.array([1, 2, 3])  # First array
arr2 = np.array([4, 5, 6])  # Second array

arr_sum = arr1 + arr2 
arr_sum

array([5, 7, 9])

In [14]:
print(arr_sum.ndim)

1


In [30]:
import pandas as pd

data = [10, 20, 30, 40]

seriesData = pd.Series(data)
seriesData

0    10
1    20
2    30
3    40
dtype: int64

In [42]:
data_dict = {'Name': ['Sunil', 'Umesh', 'Prakash','Bimal'],
             'Age': [25, 30, 35,30],
             'City': ['New York', 'Los Angeles', 'Chicago','Ohio']
            }  # Names of individuals
data_dict

{'Name': ['Sunil', 'Umesh', 'Prakash', 'Bimal'],
 'Age': [25, 30, 35, 30],
 'City': ['New York', 'Los Angeles', 'Chicago', 'Ohio']}

In [48]:
df = pd.DataFrame(data_dict)
df

Name  Age         City
0    Sunil   25     New York
1    Umesh   30  Los Angeles
2  Prakash   35      Chicago
3    Bimal   30         Ohio

In [ ]:
df['Name','Age']

In [27]:
df.iloc[1:10]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [11]:
import pandas as pd

# load data
df = pd.read_csv('Iris.csv')

In [13]:
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  146 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [17]:
# Count missing values in each column
missing_values = df.isnull().sum()  
print(missing_values)

Id               0
SepalLengthCm    2
SepalWidthCm     3
PetalLengthCm    4
PetalWidthCm     0
Species          0
dtype: int64


In [46]:
df1 = df.iloc[0:10]
df1

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa